spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.validator.apply_to_ddl: false
      javax.persistence.validation.mode: none
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/nyb_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: nyb_user
    password: nyb-user000
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

server:
  port: 3000